# This compose file defines a single validator node test network,
# along with a faucet that connects to it over json-rpc.
# In addition, it offers the following facilities:
# * JSON-RPC endpoint at http://127.0.0.1:8080.
# * chain_id of 4 / TESTING
# * The faucet can be accessed at 127.0.0.1:8000

# Additional information:
# * If you use this compose for different Diem Networks, you will need remove the db volume first.
# * If you would like to use the current Diem version within this repository, execute the
#     `build.sh` in `docker/validator` and change the image tag below to diem_e2e:latest
# * Validator images can be found at https://hub.docker.com/repository/docker/diemlabs/validator/tags
# * Faucet images can be found at https://hub.docker.com/repository/docker/diemlabs/faucet/tags

# Monitoring:
# If you want to install the monitoring components for your validator-testnet
# you can symlink the ../monitoring folder into this directory.
# Note that you will need to rename the monitoring docker-compose.yaml file to avoid duplication.
# e.g. rename it to docker-compose.mon.yaml
# You will also need to configure the network in the monitoring compose file,
# so that the container can join the same network and talk to each other.
# To start both validator and monitoring, run `docker-compose -f docker-compose.yaml -f docker-compose.mon.yaml up -d`

version: "3.8"
services:
  validator:
    # Note this image currently does not support this, will update to the appropriate minimum
    # version shortly
    image: "${VALIDATOR_IMAGE_REPO:-diemlabs/validator}:${IMAGE_TAG:-devnet}"
    networks:
      shared:
        ipv4_address:  172.16.1.10
    volumes:
      - type: volume
        source: diem-shared
        target: /opt/diem/var
      - type: bind
        source: ./validator_node_template.yaml
        target: /opt/diem/config.yaml
    command: ["/usr/local/bin/diem-node", "--test", "--test-dir", "/opt/diem/var/", "--test-config-override", "/opt/diem/config.yaml"]
    ports:
      - "8080:8080" # REST API
      - "50051:50051" # Indexer GRPC, if enabled
    expose:
      - 9101

  faucet:
    image: "${FAUCET_IMAGE_REPO:-diemlabs/faucet}:${IMAGE_TAG:-devnet}"
    depends_on:
      - validator
    networks:
      shared:
        ipv4_address:  172.16.1.11
    volumes:
      - type: volume
        source: diem-shared
        target: /opt/diem/var
    command: >
      /bin/bash -c "
        for i in {1..10}; do
          if [[ ! -s /opt/diem/var/mint.key ]]; then
            echo 'Validator has not populated mint.key yet. Is it running?'
            sleep 1
          else
            sleep 1
            /usr/local/bin/diem-faucet-service \\
              run-simple \\
              --key-file-path /opt/diem/var/mint.key \\
              --chain-id TESTING \\
              --node-url http://172.16.1.10:8080
            echo 'Faucet failed to run likely due to the Validator still starting. Will try again.'
          fi
        done
        exit 1
      "
    ports:
      - "8081:8081"

networks:
  shared:
    name: "diem-docker-compose-shared"
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  diem-shared:
    name: diem-shared
