{
 "title": "dag",
 "tags": [ "diem-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(diem_consensus_last_committed_round{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role=\"validator\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Validator Connected Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, cluster)(diem_connections{network_id=\"Validator\", role_type=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{cluster}}"
    }
   ]
  },
  {
   "title": "Synced Version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "diem_state_sync_version{type=\"synced\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{cluster}}-synced"
    }
   ]
  },
  {
   "title": "Committed user transactions per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(0.67, rate(diem_consensus_last_committed_version{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"validator\"}[$__rate_interval]) - 2 * rate(diem_consensus_last_committed_round{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"validator\"}[$__rate_interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "NUM_TXNS_PER_BLOCK",
   "type": "timeseries",
   "description": "Histogram for the number of txns per (committed) blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(diem_consensus_num_txns_per_block_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(diem_consensus_num_txns_per_block_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Odd Round: p50 latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(diem_dag_node_to_block_odd_round_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(histogram_quantile(0.5, rate(diem_dag_node_to_block_odd_round_latency_min_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(diem_dag_node_to_block_odd_round_latency_sum[$__rate_interval])/rate(diem_dag_node_to_block_odd_round_latency_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Even Round: p50 latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(diem_dag_node_to_block_even_round_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(histogram_quantile(0.5, rate(diem_dag_node_to_block_even_round_latency_min_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(diem_dag_node_to_block_even_round_latency_sum[$__rate_interval])/rate(diem_dag_node_to_block_even_round_latency_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, rate(diem_dag_node_to_block_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (cluster) (rate(diem_dag_node_to_block_latency_sum[$__rate_interval])/rate(diem_dag_node_to_block_latency_count[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(diem_dag_node_to_block_latency_sum[$__rate_interval])/rate(diem_dag_node_to_block_latency_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round Diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(diem_dag_node_round_diff_sum[$__rate_interval])/rate(diem_dag_node_round_diff_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Same Author Odd Round: p50 latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg by (cluster) (histogram_quantile(0.5, rate(diem_dag_node_to_block_same_author_odd_round_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(diem_dag_node_to_block_same_author_odd_round_latency_sum[$__rate_interval])/rate(diem_dag_node_to_block_same_author_odd_round_latency_count[$__rate_interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(histogram_quantile(0.5, rate(diem_dag_node_to_block_same_author_odd_round_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Same Author Even Round: p50 latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "avg by (cluster) (histogram_quantile(0.5, rate(diem_dag_node_to_block_same_author_even_round_latency_bucket[$__rate_interval])))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "avg(rate(diem_dag_node_to_block_same_author_even_round_latency_sum[$__rate_interval])/rate(diem_dag_node_to_block_same_author_even_round_latency_count[$__rate_interval]))",
     "legendFormat": "Overall Average"
    },
    {
     "expr": "avg(histogram_quantile(0.5, rate(diem_dag_node_to_block_same_author_even_round_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}