{
 "title": "Developer Platform Client Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_client",
    "query": {
     "query": "label_values(diem_api_request_source_client,request_source_client)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(diem_api_request_source_client,chain_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Guide",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "In order to view metrics for:\n- mainnet\n  - datasource: VictoriaMetrics Mainnet\n  - chain_name: mainnet\n- testnet\n  - datasource: VictoriaMetrics Global (Non-mainnet)\n  - chain_name: testnet\n- devnet\n  - datasource: VictoriaMetrics Global (Non-mainnet)\n  - chain_name: devnet"
   }
  },
  { "title": "Aggregations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Explanation",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "options": {
    "content": "This section contains queries that aggregate across all clients. This means the `source_client` variable above doesn't do anything."
   }
  },
  {
   "title": "Percentage of node API requests the with x-diem-client header set",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-($A/$B)", "type": "math" }
   ]
  },
  {
   "title": "Requests by client",
   "type": "piechart",
   "description": "This shows the most popular clients by request count over the configured time window. Note, the \"unknown\" value is excluded.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(request_source_client) (increase(label_replace(diem_api_request_source_client{chain_name=\"$chain_name\", request_source_client != \"unknown\"}, \"request_source_client\", \"$1\", \"request_source_client\", \"(.*)/.*\")[$__range])) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by client + version",
   "type": "piechart",
   "description": "This shows the most popular clients by request count over the configured time window. There is a separate entry per client + client version. Note, the \"unknown\" value is excluded.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(request_source_client) (increase(diem_api_request_source_client{chain_name=\"$chain_name\", request_source_client!~\"^unknown.*\"}[$__range])) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer API requests by client",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "lsql": "| #resource.type=cloud_run_revision\n| resource.labels.service_name=indexer-$chain_name \n| jsonPayload.method=* logName=*stdout\n| case {jsonPayload.diem_client!=* | jsonPayload.diem_client:=\"unknown\"; *}\n| top(jsonPayload.diem_client)",
     "repository": "gcp"
    }
   ]
  },
  {
   "title": "Per client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "source_client",
   "collapsed": true,
   "panels": [
    {
     "title": "Explanation",
     "type": "text",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 38 },
     "options": {
      "content": "This section contains queries that show data for a specific client. To select which client to view metrics for, select one in the `source_client` variable dropdown above."
     }
    },
    {
     "title": "Top 5 endpoints",
     "type": "piechart",
     "description": "This shows what are the top 5 most common endpoints called by users of this client in the configured time window.",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by(operation_id) (increase(diem_api_request_source_client{request_source_client=\"$source_client\", chain_name=\"$chain_name\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}