{
 "title": "logging",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   { "name": "AggInterval", "label": "Aggregation Interval", "query": "1m,5m,15m,30m,1h,3h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Overview Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logging Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "The rate of logs written via the code.  This is a superset of logs written through to the end log storage system.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "logs/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Log Send Process Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Rate of processing logs to send to the logging pod.  This will drop to 0 if stuck in a continuous connection loop due to an unavailable logging pod.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "logs/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_struct_log_processed_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Log Written to Logging Pod Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Rate of logs successfully written to the logging pod.  This number will drop if there are networking issues or backpressure from the central logging.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "logs/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_struct_log_tcp_submit_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Processed Logs / Logs Written ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Ratio of processed logs to logs written.  As this value drops for a long period of time below 100%, shows that the logging system is falling behind due to connection or backpressure issues.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(diem_struct_log_processed_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])/rate(diem_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Logs Sent / Logs Written ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Ratio of logs sent (to logging pod) to logs written (e.g. info!).  As this value drops below 100% for a long time, it shows issues with the logging system falling behind due to backpressure and possibly underscaled downstream processing.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(diem_struct_log_tcp_submit_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])/rate(diem_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Logger Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connect To Logstash Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Rate at which a node tries to connect to Logstash.  Ideally, it should only happen on startup of a node.  A large number of connections could indicate a networking issue or a lot of backpressure from Logstash.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "connects/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_struct_log_tcp_connect_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Connect Error Rate  ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Percentage of connections that fail to connect to the logging pod.  Extended or high percentage e.g. 100% connections points to a dead logging pod.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Connections Failed" }
   ],
   "targets": [
    {
     "expr": "(rate(diem_struct_log_connect_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]) or 0 * rate(diem_struct_log_tcp_connect_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])) / rate(diem_struct_log_tcp_connect_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Logging Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logging Total Failure Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "The end to end rate of logs being submitted, to actually being sent to Logstash.  If this value rises above 0, see the corresponding error graphs to determine the issue.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Dropped" }
   ],
   "targets": [
    {
     "expr": "1-(rate(diem_struct_log_tcp_submit_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])/rate(diem_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total Dropped Logs Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "The total number of logs dropped per second",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "none", "label": "logs/s" }
   ],
   "targets": [
    {
     "expr": "(rate(diem_struct_log_send_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$AggInterval]) or\n      rate(diem_struct_log_queue_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$AggInterval]) * 0) + (rate(diem_struct_log_send_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$AggInterval]) * 0 or rate(diem_struct_log_queue_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Log Queue Error Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Rate at which the log system has enough backpressure that the in memory log queue has been filled.  This represents either backpressure from the downstream Elasticsearch DB / logstashes that too much data is being sent, or that there are networking issues that are causing the node to not be able to send logs.  If this metric is above 0, logs are being lost.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent of logs" }
   ],
   "targets": [
    {
     "expr": "(rate(diem_struct_log_queue_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$AggInterval]) or 0 * rate(diem_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$AggInterval]))/rate(diem_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Send To Logstash Error Rate  ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Percent of logs that fail\n\nP of failures to send logs to Logstash.  This can be because of backpressure or networking issues, and when it's been occurring often, it may cause the queue errors to occur.  This metric going up does not necessarily mean loss of logs, as there is at least 1 retry at sending the log line when it fails to be sent.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent of logs" }
   ],
   "targets": [
    {
     "expr": "(rate(diem_struct_log_send_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$AggInterval]) or 0 * rate(diem_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$AggInterval]))/rate(diem_struct_log_processed_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  }
 ]
}