{
 "title": "node-system-info",
 "tags": [ "diem-core" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"},kubernetes_pod_name)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"},role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Info",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_del(node_system_cpu_info{metrics_source=\"$metrics_source\", chain_name=\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}, \"metrics_source\", \"chain_name\", \"namespace\", \"__name__\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Info",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(brand) (node_system_cpu_info{metrics_source=\"$metrics_source\", chain_name=\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count by (kubernetes_pod_name, role) (node_system_cpu_usage{metrics_source=\"$metrics_source\", chain_name=\"$chain_name\"}) - 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total System Memory",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "label_del(node_system_mem_total{chain_name=\"$chain_name\", metrics_source=\"$metrics_source\"}, \"__name__\", \"metrics_source\", \"namespace\", \"chain_name\")",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}