{
 "title": "safety-rules",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Safety Rules Query Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Counts of Safety Rules Queries",
   "type": "graph",
   "description": "This panel displays the error counts encountered by safety rules queries within the last aggregation interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    {
     "format": "short",
     "label": "Error Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", result=\"error\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}_{{method}}"
    }
   ]
  },
  { "title": "Safety Rules Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Epoch",
   "type": "graph",
   "description": "The most recent epoch processed by safety rules",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Epoch Number" }
   ],
   "targets": [
    {
     "expr": "diem_safety_rules_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", field=\"epoch\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {}
   ]
  },
  {
   "title": "Last Voted Round",
   "type": "graph",
   "description": "The last round that the validator submitted a vote",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Round Number" }
   ],
   "targets": [
    {
     "expr": "diem_safety_rules_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", field=\"last_voted_round\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Preferred Round",
   "type": "graph",
   "description": "The highest parent round from any incoming quorum certificate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Round Number" }
   ],
   "targets": [
    {
     "expr": "diem_safety_rules_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", field=\"preferred_round\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Waypoint Version",
   "type": "graph",
   "description": "Current waypoint version of persistent safety storage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Waypoint Version" }
   ],
   "targets": [
    {
     "expr": "diem_safety_rules_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", field=\"waypoint_version\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Safety Rules Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Initialize",
   "type": "graph",
   "description": "This method initializes safety rules using an epoch ending ledger info.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", method=\"initialize\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}_{{result}}"
    }
   ]
  },
  {
   "title": "Consensus State",
   "type": "graph",
   "description": "This method provides the internal state of safety rules for monitoring and/or debugging purposes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", method=\"consensus_state\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}_{{result}}"
    }
   ]
  },
  {
   "title": "Construct and Sign Vote",
   "type": "graph",
   "description": "This method attempts to vote for a given proposal following the voting rules.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", method=\"construct_and_sign_vote\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}_{{result}}"
    }
   ]
  },
  {
   "title": "Sign Proposal",
   "type": "graph",
   "description": "This method is called to sign a proposal or block.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", method=\"sign_proposal\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}_{{result}}"
    }
   ]
  },
  {
   "title": "Sign Timeout",
   "type": "graph",
   "description": "This method is called to sign a timeout.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", method=\"sign_timeout\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}_{{result}}"
    }
   ]
  }
 ]
}