{
 "title": "state-sync-v2",
 "description": "State sync v2 dashboard",
 "tags": [ "diem-core" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, role)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "State Sync Driver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest synced version",
   "type": "timeseries",
   "description": "The latest synced version of the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "diem_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"synced\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Latest synced version",
   "type": "bargauge",
   "description": "The latest synced version.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"synced\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Sync lag (behind highest known)",
   "type": "timeseries",
   "description": "The difference between the highest advertised version and the currently synced version.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "clamp_min(diem_data_client_highest_advertised_data{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", data_type=\"transactions\"} - on(kubernetes_pod_name,role, run_uuid) diem_state_sync_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"synced\"}, 0)",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Syncing throughput (versions per second)",
   "type": "timeseries",
   "description": "The storage synchronizer throughput (versions per second).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(diem_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",type=\"synced\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{type}}"
    },
    {
     "expr": "rate(diem_state_sync_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",type=\"synced_states\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{type}}"
    }
   ]
  },
  {
   "title": "Latest synced epoch",
   "type": "timeseries",
   "description": "The highest synced epoch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "diem_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"synced_epoch\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{type}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer versions (per operation)",
   "type": "timeseries",
   "description": "The storage synchronizer version per operation type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "diem_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{type}}"
    }
   ]
  },
  {
   "title": "Driver events (per second)",
   "type": "timeseries",
   "description": "The driver events per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(diem_state_sync_driver_counters{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Executing component",
   "type": "timeseries",
   "description": "The component currently executing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(diem_state_sync_executing_component_counters{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) > 0",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Execute/Apply latencies",
   "type": "timeseries",
   "description": "The latencies of execute/apply operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(diem_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"execute_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Execute (P99)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(diem_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"apply_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Apply (P99)"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(diem_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"execute_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Execute (P70)"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(diem_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"apply_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Apply (P70)"
    }
   ]
  },
  {
   "title": "Commit latencies",
   "type": "timeseries",
   "description": "The latencies of commit operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(diem_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"commit_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Commit (P99)"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(diem_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"commit_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Commit (P70)"
    }
   ]
  },
  {
   "title": "Execute/Apply chunk sizes",
   "type": "piechart",
   "description": "Histogram counts of the chunk sizes used when executing or applying transactions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(diem_state_sync_storage_synchronizer_chunk_sizes_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of state values (on-chain)",
   "type": "timeseries",
   "description": "The number of state values currently held on-chain.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "diem_jellyfish_leaf_count{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer gauges",
   "type": "timeseries",
   "description": "The storage synchronizer gauges",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "diem_state_sync_storage_synchronizer_gauges{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer errors (per second)",
   "type": "timeseries",
   "description": "The storage synchronizer errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rate(diem_state_sync_storage_synchronizer_errors{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Bootstrapper errors (per second)",
   "type": "timeseries",
   "description": "The bootstrapper errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(diem_state_sync_bootstrapper_errors{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Continuous syncer errors (per second)",
   "type": "timeseries",
   "description": "The continuous syncer errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(diem_state_sync_continuous_syncer_errors{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Data Streaming Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active data streams",
     "type": "timeseries",
     "description": "The number of active data streams.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "diem_data_streaming_service_active_data_streams{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Created data streams (per second)",
     "type": "timeseries",
     "description": "The data streams created per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(diem_data_streaming_service_create_data_stream{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Terminated data streams (per second)",
     "type": "timeseries",
     "description": "The data streams terminated per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(diem_data_streaming_service_terminate_data_stream{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{feedback_type}}"
      }
     ]
    },
    {
     "title": "Data stream send failures",
     "type": "timeseries",
     "description": "The number of send failures encountered.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "diem_data_streaming_service_stream_send_failure{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Sent data requests (per second)",
     "type": "timeseries",
     "description": "The sent data requests per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(diem_data_streaming_service_sent_data_requests{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Received data responses (per second)",
     "type": "timeseries",
     "description": "The data responses received per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "rate(diem_data_streaming_service_received_data_response{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Retried data requests (per second)",
     "type": "timeseries",
     "description": "The retried data requests per second (with new timeouts in ms).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "rate(diem_data_streaming_service_retried_data_requests{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{request_timeout}}"
      }
     ]
    },
    {
     "title": "Received response errors (per second)",
     "type": "timeseries",
     "description": "The data response errors received per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(diem_data_streaming_service_received_response_error{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    },
    {
     "title": "Average request processing latencies (per type)",
     "type": "timeseries",
     "description": "The average request processing latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "diem_data_streaming_service_data_request_processing_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/diem_data_streaming_service_data_request_processing_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Request processing latencies (0.99 quantile)",
     "type": "timeseries",
     "description": "The 0.99 quantile of all request processing latencies.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_data_streaming_service_data_request_processing_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{request_type}}"
      }
     ]
    },
    {
     "title": "Check progress errors (per second)",
     "type": "timeseries",
     "description": "The check progress errors encountered per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "rate(diem_data_streaming_service_check_progress_error{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    },
    {
     "title": "In-flight data requests",
     "type": "timeseries",
     "description": "The number of pending in-flight data requests",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "diem_data_streaming_service_pending_data_responses{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    },
    {
     "title": "Global data summary errors (per second)",
     "type": "timeseries",
     "description": "The global data summary errors encountered per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(diem_data_streaming_service_global_summary_error{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Diem Data Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "In-flight polls",
     "type": "timeseries",
     "description": "The number of in-flight polls currently executing",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "diem_data_client_in_flight_polls{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{peer_type}}"
      }
     ]
    },
    {
     "title": "Connected peers (including priorities)",
     "type": "timeseries",
     "description": "The number of connected peers by priority types",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "diem_data_client_connected_peers{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{peer_type}}"
      }
     ]
    },
    {
     "title": "Sent requests (per second)",
     "type": "timeseries",
     "description": "The sent data requests per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "rate(diem_data_client_sent_requests{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_types}}"
      }
     ]
    },
    {
     "title": "Successful responses (per second)",
     "type": "timeseries",
     "description": "The successful data responses per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "rate(diem_data_client_success_responses{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Error responses (per second)",
     "type": "timeseries",
     "description": "The error responses per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "rate(diem_data_client_error_responses{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Average request latencies (per type)",
     "type": "timeseries",
     "description": "The average request latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "diem_data_client_request_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/diem_data_client_request_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network}}"
      }
     ]
    },
    {
     "title": "Request latencies",
     "type": "timeseries",
     "description": "The latencies of all requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_data_client_request_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(diem_data_client_request_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    },
    {
     "title": "Optimal chunk sizes (per type)",
     "type": "timeseries",
     "description": "The optimal chunk sizes per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "diem_data_client_optimal_chunk_sizes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{data_type}}"
      }
     ]
    },
    {
     "title": "Highest advertised transaction data",
     "type": "bargauge",
     "description": "The highest advertised transaction data.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "diem_data_client_highest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",data_type=\"transactions\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Highest advertised data (per type)",
     "type": "timeseries",
     "description": "The highest advertised data version per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "diem_data_client_highest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{data_type}}"
      }
     ]
    },
    {
     "title": "Lowest advertised transaction data",
     "type": "bargauge",
     "description": "The lowest advertised transaction data.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "diem_data_client_lowest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",data_type=\"transactions\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Lowest advertised data (per type)",
     "type": "timeseries",
     "description": "The lowest advertised data version per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "diem_data_client_lowest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{data_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Service Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests received (per second)",
     "type": "timeseries",
     "description": "The requests received per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "rate(diem_storage_service_server_requests_received{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Storage responses sent (per second)",
     "type": "timeseries",
     "description": "The storage responses sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "rate(diem_storage_service_server_responses_sent{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{response_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Request processing latencies",
     "type": "timeseries",
     "description": "The latencies for storage request processing",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_storage_service_server_request_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(diem_storage_service_server_request_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    },
    {
     "title": "Average request processing latencies (per type)",
     "type": "timeseries",
     "description": "The average request processing latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "diem_storage_service_server_request_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/diem_storage_service_server_request_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Pending network events (per second)",
     "type": "timeseries",
     "description": "The pending network events per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "rate(diem_storage_service_server_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{state}}"
      }
     ]
    },
    {
     "title": "Storage errors (per second)",
     "type": "timeseries",
     "description": "The storage errors per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "rate(diem_storage_service_server_errors{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Active optimistic fetches",
     "type": "timeseries",
     "description": "The number of active optimistic fetches at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "diem_storage_service_server_optimistic_fetch_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "New optimistic fetch events",
     "type": "timeseries",
     "description": "New optimistic fetch events seen at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(diem_storage_service_server_optimistic_fetch_event{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",event=\"optimistic_fetch_add\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Expired optimistic fetch events",
     "type": "timeseries",
     "description": "Expired optimistic fetch events seen at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(diem_storage_service_server_optimistic_fetch_event{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",event=\"optimistic_fetch_expire\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Optimistic fetch latencies",
     "type": "timeseries",
     "description": "The latencies for handling optimistic fetch requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_storage_service_server_optimistic_fetch_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(diem_storage_service_server_optimistic_fetch_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    },
    {
     "title": "Average optimistic fetch latencies",
     "type": "timeseries",
     "description": "The average latencies to handle optimistic fetch requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "diem_storage_service_server_optimistic_fetch_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/diem_storage_service_server_optimistic_fetch_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Number of ignored peers",
     "type": "timeseries",
     "description": "The number of peers currently being ignored",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "diem_storage_service_server_ignored_peer_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "LRU storage cache (Hit Rate)",
     "type": "timeseries",
     "description": "The hit rate (percentage) of the LRU storage cache per cache probe.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, role, network_id) (diem_storage_service_server_lru_cache{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", event=\"lru_cache_hit\"}) / sum by (kubernetes_pod_name, role, network_id) (diem_storage_service_server_lru_cache{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", event=\"lru_cache_probe\"}) * 100\n",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Compression ratio (sent)",
     "type": "timeseries",
     "description": "The compression ratios of sent network messages (i.e., compressed bytes / raw bytes)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, role, client) (diem_compression_byte_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", data_type=\"compressed_bytes\"}) / sum by (kubernetes_pod_name, role, client) (diem_compression_byte_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", data_type=\"raw_bytes\"}) * 100\n",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{client}}"
      }
     ]
    },
    {
     "title": "Network frame overflow (count per second)",
     "type": "timeseries",
     "description": "The rate of network frame overflows when handling storage requests (per second).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(diem_storage_service_server_network_frame_overflow{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{response_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average propose to sync latencies (seconds)",
     "type": "timeseries",
     "description": "The average latencies taken from when data is first proposed, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "rate(diem_data_client_sync_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_sync_latency\"}[1m])/rate(diem_data_client_sync_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_sync_latency\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{label}}"
      }
     ]
    },
    {
     "title": "Propose to sync latencies (seconds)",
     "type": "timeseries",
     "description": "The latencies taken from when data is first proposed, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(diem_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    },
    {
     "title": "Average propose to seen latencies (seconds)",
     "type": "timeseries",
     "description": "The average latencies taken from when data is first proposed, to when it is finally seen.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "targets": [
      {
       "expr": "rate(diem_data_client_sync_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_seen_latency\"}[1m])/rate(diem_data_client_sync_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_seen_latency\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{label}}"
      }
     ]
    },
    {
     "title": "Propose to seen latencies (seconds)",
     "type": "timeseries",
     "description": "The latencies taken from when data is first proposed, to when it is finally seen.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_seen_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(diem_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_seen_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    },
    {
     "title": "Average seen to sync latencies (seconds)",
     "type": "timeseries",
     "description": "The average latencies taken from when data is first seen, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "targets": [
      {
       "expr": "rate(diem_data_client_sync_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"seen_to_sync_latency\"}[1m])/rate(diem_data_client_sync_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"seen_to_sync_latency\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{label}}"
      }
     ]
    },
    {
     "title": "Seen to sync latencies (seconds)",
     "type": "timeseries",
     "description": "The latencies taken from when data is first seen, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(diem_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"seen_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(diem_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"seen_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    }
   ]
  }
 ]
}